import LeftPanel from "../../Components/LeftPanel";
import Model from "../../Components/Model";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Spotify Music",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-[100%] flex">
          <div className="w-[23%] overflow-y-auto h-[86vh]">
            <LeftPanel />
          </div>
          <div className="w-[77%] h-[86vh] overflow-y-auto bg-[#1D1D1D]">
            {children}
          </div>
        </div>
        <div className="h-[14vh]">
          <Model />
        </div>
      </body>
    </html>
  );
}
