import { Inter } from "next/font/google";
import LoginNavbar from "../../Components/LogedinNavbar/LogedinNavbar";
import Model from "../../Components/Model";
import LeftPanel from "../../Components/LeftPanel";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-[100%]">
          <LoginNavbar />
        </div>
        <div className="w-[100%] flex ">
          <div className="w-[20%]">
            <LeftPanel />
          </div>
          <div className="w-[80%]">{children}</div>
        </div>
        <div className="h-[11vh]">
          <Model />
        </div>
      </body>
    </html>
  );
}
